export default {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GOOGLE_LOGIN_REQUEST: 'GOOGLE_LOGIN_REQUEST',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILURE: 'GOOGLE_LOGIN_FAILURE',
  LINKEDIN_LOGIN_REQUEST: 'LINKEDIN_LOGIN_REQUEST',
  LINKEDIN_LOGIN_SUCCESS: 'LINKEDIN_LOGIN_SUCCESS',
  LINKEDIN_LOGIN_FAILURE: 'LINKEDIN_LOGIN_FAILURE',
};
