export const links = {
  iTechVK: 'https://vk.com/itechart.group',
  iTechYoutube: 'https://www.youtube.com/user/iTechArt',
  iTechFacebook: 'https://www.facebook.com/iTechArt.Group',
  linkedInURL: 'users/auth/linkedin',
  googleURL: 'users/auth/google',
  resetRoute: 'users/forgot-password',
  changePasswordRoute: 'users/change-password',
  loginRoute: 'users/login',
  registrationRoute: 'users/registration',
  publicProfileRoute: 'profile/public',
  coursePreviewRoute: 'course/preview/',
  twitter:'http://twitter.com/',
  facebook:'https://www.facebook.com/',
  linkedIn:'https://www.linkedin.com/',
};
