export const links = {
  iTechVK: 'https://vk.com/itechart.group',
  iTechYoutube: 'https://www.youtube.com/user/iTechArt',
  iTechFacebook: 'https://www.facebook.com/iTechArt.Group',
  linkedInURL: 'api/users/auth/linkedin',
  googleURL: 'api/users/auth/google',
  resetRoute: 'users/forgot-password',
  changePasswordRoute: 'users/change-password',
  loginRoute: 'users/login',
  registrationRoute: 'users/registration',
  publicProfileRoute: 'profile/public',
  coursesCarouselRoute:'course/carousel',
  searchCourses: 'course',
  coursePreviewRoute: 'course/preview/',
  twitter:'http://twitter.com/',
  facebook:'https://www.facebook.com/',
  linkedIn:'https://www.linkedin.com/',
  coursePreview: 'course/preview/',
  placeHolderImage: 'http://placeimg.com/640/480/tech',
  subscribeCourse: 'course/subscribe',
  subscribeCourseCheck: 'course/subscribe/check'
};
